SET DEFINE OFF;

Prompt Table SG_APEX_APPLICATIONS;
CREATE TABLE SG_APEX_APPLICATIONS
(
  APP_ID                NUMBER,
  APP_NAME              VARCHAR2(200  BYTE),
  APP_description       VARCHAR2(1000 BYTE),
  APP_OVERVIEW          VARCHAR2(4000 BYTE), 
  APP_EXPECT_INPUT      VARCHAR2(200  BYTE),
  APP_EXPECT_COMPLETED  VARCHAR2(200  BYTE),
  APP_EXPECT_NBR_USERS  VARCHAR2(200  BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/



Prompt Trigger SG_APEX_APP_BI;
CREATE OR REPLACE TRIGGER SG_APEX_APP_BI
BEFORE INSERT ON SG_APEX_APPLICATIONS
FOR EACH ROW
DECLARE

  APPID NUMBER;
  
BEGIN
        
        SELECT SG_APEX_APP_SEQ.NEXTVAL 
        INTO APPID
        FROM DUAL;
    
         
        :new.APP_ID := APPID;
        
END;
/
SHOW ERRORS;
/


insert into  SG_APEX_APPLICATIONS(APP_NAME) 
select MODULE
 from APEX_WEEKLY_REPORT
/



select  * from SG_APEX_APPLICATIONS 
/


EDIT SG_APEX_APPLICATIONS