CREATE TABLE SQA_WEEKLY_REPORT
(
 REPORT_DATE         DATE,
 MODULE              VARCHAR2(200 BYTE),
 LOADED              NUMBER,
 WORKING             NUMBER,
 COMPLETED           NUMBER
 )
/



CREATE OR REPLACE TRIGGER SQA_WEEKLY_REPORT_BI
BEFORE INSERT ON SQA_WEEKLY_REPORT
FOR EACH ROW
DECLARE
  P_DATE   DATE;

BEGIN

        SELECT SYSDATE 
        INTO P_DATE
        FROM DUAL;

        :new.REPORT_DATE := P_DATE;
        
END;
/
SHOW ERRORS;


INSERT INTO SQA_WEEKLY_REPORT ( MODULE, LOADED,WORKING, COMPLETED)
SELECT 'SQA_ICC' AS MODULE,
       COUNT(A.LOANNUMBER) AS LOADED_CNT, 
       SUM(CASE WHEN A.COMPLETED = 0  then 1 ELSE 0 END) AS WORKING_CNT,
       SUM(CASE WHEN b.pid is not null then 1 ELSE 0 END) AS COMPLETED_CNT
from RDM.SQA_ICC_BACKLOG@APXP01.PROP.SGPCORP.LOCAL A
left join ( select * from RDM.SQA_ICC_PRIOR_LOAN_HISTORY@APXP01.PROP.SGPCORP.LOCAL
                     ) b on (a.pid = b.pid)
where TRUNC(a.DATE_UPLOADED) > TRUNC(SYSDATE) - 7
UNION ALL
SELECT 'SQA_TDA' AS MODULE, 
SUM(A.NBR_WORKORDERS) AS LOADED_CNT,
       SUM(CASE WHEN B.WORKING = 'Y' AND B.COMPLETED IS NULL THEN 1 ELSE 0 END) WORKING_CNT,
       SUM(CASE WHEN B.WORKING = 'Y' AND B.COMPLETED = 'Y'   THEN 1 ELSE 0 END)  COMPLETED_CNT
from rdm.sqa_vendor_list@APXP01.PROP.SGPCORP.LOCAL A  
left join ( select WORKING, COMPLETED, BATCH_NO from RDM.SQA_TD_DATA@APXP01.PROP.SGPCORP.LOCAL
                     ) b on (a.BATCH_NO = b.BATCH_NO)
UNION ALL                    
SELECT 'SQA_QC' AS MODULE, 
        COUNT(LOAN_NUMBER) AS LOAD_CNT,
        NVL(SUM(CASE WHEN A.WORKING > 0  then 1 ELSE 0 END),0) AS WORKING_CNT,
        NVL(SUM(CASE WHEN A.COMPLETED IS NOT NULL THEN 1 ELSE 0 END),0) COMPLETE_CNT
        FROM RDM.SQA_QC_DETAILS@APXP01.PROP.SGPCORP.LOCAL A
WHERE TRUNC(START_DATE) > TRUNC(SYSDATE) - 7     
UNION ALL                 
SELECT 'SQA_REOINT' AS MODULE,
       COUNT(LOAN_NUM) AS LOADED_CNT, 
       SUM(CASE WHEN WORKING = 'Y' then 1 ELSE 0 END) AS WORKING_CNT,
       SUM(CASE WHEN COMPLETED = 'Y' then 1 ELSE 0 END) AS COMPLETED_CNT
FROM RDM.SQA_REOINT_DATA@APXP01.PROP.SGPCORP.LOCAL A
WHERE TRUNC(FILE_UPLOAD_DT) > TRUNC(SYSDATE)-7

/
